### ISSUE TITLE
Rate-limit or disable DNS lookups?

### ISSUE THREAD

**Issue by jermudgeon** [javadmohebbi/goNfCollector#10]
Thanks for building this project. Is there a way to rate-limit or disable reverse DNS lookups?

**Comment by javadmohebbi** [comment]
Hi @jermudgeon 

In the next release reverse DNS lookup will be removed completely due to a known issue and this will fix the performance problem temporary. After that I will improve it as an optional feature. 
Unfortunately currently you can not disable it ;-)

**Comment by jermudgeon** [comment]
Thank you. I will subscribe to product releases. :)
