### ISSUE TITLE
Can't find nfcollector-logger

### ISSUE THREAD

**Issue by Alexandre-Santos** [javadmohebbi/goNfCollector#22]
Hi,

In another post, there was a suggestion to use a tool for debugging which fields were captured. The commands to execute the tool were the following:

`cd $HOME/oi24/nfcollector`
`docker-compose down`
`wget -O /tmp/nfcollector-logger https://github.com/javadmohebbi/goNfCollector/raw/main/build/linux/amd64/nfcollector-logger`
`chmod +x /tmp/nfcollector-logger`
`sudo /tmp/nfcollector-logger`

However, I could not find the binary of nfcollector-logger neither on the project files nor on the link. Where can I download this tool? Or what can I do to achieve similar results?

**Comment by javadmohebbi** [comment]
Hi @Alexandre-Santos,

Thank you for reporting the missing file. Now you can download the mentioned binary.

**Comment by Alexandre-Santos** [comment]
Thank you, Javad.
