### ISSUE TITLE
Will Prometheus be supported? 

### ISSUE THREAD

**Issue by benisai** [javadmohebbi/goNfCollector#32]
Hi, I'm trying to stay away from influx as it's really heavy on memory. Will Prometheus be supported?

**Comment by china-zhoujie** [comment]
Hello, I would like to ask how to configure import into mysql?

**Comment by javadmohebbi** [comment]
Hi there, for now, InfluxDB is not supported and we are going to use Postgres as our main DB. the connection between NetflowCollector and Grafana will be deployed through REST API

**Comment by china-zhoujie** [comment]
> 您好，目前不支持 InfluxDB，我们将使用 Postgres 作为我们的主数据库。NetflowCollector 和 Grafana 之间的连接将通过 REST API 部署
Hello, I would like to ask, how to set import to mysql?

**Comment by javadmohebbi** [comment]
@china-zhoujie Not now, but in the next version postgres will be supported!
