### ISSUE TITLE
nfcollector docker is not starting on RPI4 - DietPi - ARM64

### ISSUE THREAD

**Issue by Cebrain** [javadmohebbi/goNfCollector#34]
Hey guys,

i have the problem that i cant start nfcollector docker container, getting the following error:

`exec /opt/nfcollector/bin/nfcollector: exec format error`

OS
DietPi x64
Raspberry Pi 4

**Comment by Cebrain** [comment]
Oh i think i found the problem, it is really because the architecture. Is there anything for ARM planned?

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by javadmohebbi** [comment]
Hi @Cebrain 

Thank you for your message and suggestion. In the next version, I will compile solution for ARM architecture

Regards,

**Comment by r3df0chs** [comment]
This would be awesome
@javadmohebbi any ETA when you have the next version planned?
Would like to test
