### ISSUE TITLE
Can not access oi24

### ISSUE THREAD

**Issue by sunks98** [javadmohebbi/goNfCollector#37]
Hi,

I just ran shell script `latest.sh` with error codes 522 and 523, and could not access the website [https://openintelligence24.com](https://openintelligence24.com) , is there something wrong with the server?

Thanks a lot in advance for your help,
Kaisheng Sun.

**Comment by javadmohebbi** [comment]
Hi @sunks98 

Yes, our provider faced an cyber attack and now our website is not accessible! I am really sorry for this issue. If they could not fix this issue soon, I will let you have an alternate way to deploy the app ;-)

**Comment by sunks98** [comment]
Okay, I see. Thank you very much for taking the time to reply~ ;-)

**Comment by MatKra84** [comment]
Any update about oi24 website ?

**Comment by javadmohebbi** [comment]
Hi @sunks98 and @MatKra84 

Please follow the [README.md](https://github.com/javadmohebbi/goNfCollector/blob/main/README.md#all-in-one-deployment-using-docker-compose) to deploy this app.

If you need a quick guide to deploy this app on your own linux OS, follow the further steps:
```
wget -O latest.sh https://raw.githubusercontent.com/javadmohebbi/goNfCollector/main/dockerize/build-up-from-github.sh
chmod +x latest.sh
./latest.sh
```

In order to prevent the issues in the future, we moved all the required installation files to this GitHub Repo.

**Comment by MatKra84** [comment]
Thank you :-)

> In order to prevent the issues in the future, we moved all the required installation files to this GitHub Repo.

**Comment by sunks98** [comment]
> Hi @sunks98 and @MatKra84
> 
> Please follow the [README.md](https://github.com/javadmohebbi/goNfCollector/blob/main/README.md#all-in-one-deployment-using-docker-compose) to deploy this app.
> 
> If you need a quick guide to deploy this app on your own linux OS, follow the further steps:
> 
> ```
> wget -O latest.sh https://raw.githubusercontent.com/javadmohebbi/goNfCollector/main/dockerize/build-up-from-github.sh
> chmod +x latest.sh
> ./latest.sh
> ```
> 
> In order to prevent the issues in the future, we moved all the required installation files to this GitHub Repo.

Thank you!!! ;-)
