### ISSUE TITLE
Install without docker?

### ISSUE THREAD

**Issue by vladosam** [javadmohebbi/goNfCollector#5]
Is there tutorial for a standalone installation? I already have grafana and influxdb setup and i don't want to use docker. I did manage to use older Netflow Collector v0.0.9 but it maxed my cpu to 100% as soon as it starts. Thanks.

**Comment by javadmohebbi** [comment]
Hi @vladosam 

I am working on non-docker installation and will be ready within a week. I will let you know once it's available

**Comment by vladosam** [comment]
Excellent. Thank you. I will close this issue.
