### ISSUE TITLE
Source and Destination mask information missing on influxdb bucket

### ISSUE THREAD

**Issue by Alexandre-Santos** [javadmohebbi/goNfCollector#9]
Hi,

Congrats @javadmohebbi on this great tool, it provides a great resource to analyze traffic and support network administration.

I am trying to group data using the destination mask as a criterion. However, when consulting the influxdb data explorer I can't find any mask related information. I am currently monitoring V5 and V9 devices and the default collector's configuration seems to take the network masks into account so what could I be missing?

Thank you for your help.

**Comment by javadmohebbi** [comment]
Hi @Alexandre-Santos 

Currently Src&Dst mask are not stored in the DB. I will include them in the next minor version.
